server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Single Page Application (SPA) routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy Auth Service Requests
    location /api/auth/ {
        proxy_pass http://bank-auth-service:9090/api/auth/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Proxy Account Service Requests
    location /api/accounts {
        proxy_pass http://bank-account-service:8082/api/accounts;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy Transfer Flow Service Requests (Specific route)
    location /api/transactions/transfer {
        proxy_pass http://transfer-flow-service:8083/api/transactions/transfer;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy Deposit/Withdraw/Transaction Service Requests
    location /api/transactions {
        proxy_pass http://bank-transaction-service:8086/api/transactions;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy Fraud Detection .NET Service Requests
    location /api/Fraud {
        proxy_pass http://fraud-detection-service:5000/api/Fraud;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy AI Chatbot Service Requests
    location /api/Chat {
        proxy_pass http://fraud-detection-service:5000/api/Chat;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Proxy Admin Service Requests
    location /api/admin/ {
        proxy_pass http://bank-admin-service:9098/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
